### ISSUE TITLE
Replica Sets echo.yaml references GCP project ID "hightowerlabs" explicitly

### ISSUE THREAD

**Issue by DazWilkin** [kelseyhightower/gke-service-accounts-tutorial#1]
This won't match the PROJECT_ID in use by the reader.

The reader ought be encouraged to swap this out with the value of bash variable, perhaps:

    sed -i s/"value: \"hightowerlabs\""/"value: \"${PROJECT_ID}\""/g echo-rs.yaml

**Comment by kelseyhightower** [comment]
Fixed on master.
